const PATH_ICONS = '../../assets/icons/';

export const ROUTERS_ICONS_MAP = {
  'email': PATH_ICONS + 'icon_mail.png',
  'lock': PATH_ICONS + 'icon_lock.png',
  'adoption': PATH_ICONS + 'icon_adoption.png',
  'home': PATH_ICONS + 'icon_home.png',
  'logout': PATH_ICONS + 'icon_logout.png',
  'manage_search': PATH_ICONS + 'icon_manage_search.png',
  'monitor_heart': PATH_ICONS + 'icon_monitor_heart.png',
  'monitoring': PATH_ICONS + 'icon_monitoring.png',
  'person_add': PATH_ICONS + 'icon_person_add.png',
  'person_search': PATH_ICONS + 'icon_person_search.png',
  'person': PATH_ICONS + 'icon_person.png',
  'pets': PATH_ICONS + 'icon_pets.png',
  'search': PATH_ICONS + 'icon_search.png',
  'sound_detection_dog_barking': PATH_ICONS + 'icon_sound_detection_dog_barking.png',
  'volunteer_activism': PATH_ICONS + 'icon_volunteer_activism.png',
  'add_circle': PATH_ICONS + 'icon_add_circle.png',
  'wysiwyg': PATH_ICONS + 'icon_wysiwyg.png',
  'add_card': PATH_ICONS + 'icon_add_card.png',
  'payments': PATH_ICONS + 'icon_payments.png',
  'input': PATH_ICONS + 'icon_input.png',
  'inventory': PATH_ICONS + 'icon_inventory.png',
  'output': PATH_ICONS + 'icon_output.png',
  'set_meal': PATH_ICONS + 'icon_set_meal.png',
}
